// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace GlyCounter
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "timsrust_ffi";





        [DllImport(__DllName, EntryPoint = "open_reader", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint open_reader(byte* path);

        [DllImport(__DllName, EntryPoint = "get_spectrum", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* get_spectrum(nuint handle, nuint index);

        [DllImport(__DllName, EntryPoint = "get_spectrum_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern nuint get_spectrum_count(nuint handle);

        [DllImport(__DllName, EntryPoint = "free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_string(byte* s);

        /// <summary>
        ///  Closes and drops a reader handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "close_reader", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void close_reader(nuint handle);


    }



}
