name: Build and Release

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: GlyCounter/GlyCounter.sln
      Configuration: Release
      # Ensure there's only one 'GlyCounter' subfolder in the path below
      Project_Path: GlyCounter/GlyCounter.csproj
      Release_Directory: ./Releases
      App_Package_ID: GlyCounter

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install .NET Windows Desktop Workload
        run: dotnet workload install windowsdesktop

      - name: Calculate version
        # (Your versioning script steps here, same as before)
        ...

      - name: Restore dependencies
        run: dotnet restore $env:Solution_Name

      - name: Build
        run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore

      - name: Test
        run: dotnet test $env:Solution_Name --configuration $env:Configuration --no-build --verbosity normal

      - name: Publish Application Executable
        shell: pwsh
        run: |
          dotnet publish $env:Project_Path `
            --configuration $env:Configuration `
            --output ./publish `
            --no-build `
            --self-contained true `
            -r win-x64 `
            /p:PublishSingleFile=false `
            /p:IncludeNativeLibrariesForSelfExtract=false

          if (-not (Test-Path "./publish/GlyCounter.exe")) {
            Write-Host "ERROR: GlyCounter.exe not found after publish."
            exit 1
          }

      - name: Install Velopack Tool (vpk)
        run: dotnet tool install -g vpk --ignore-failed-sources

      - name: Run Velopack Pack
        shell: pwsh
        run: |
          vpk pack --packId $env:App_Package_ID `
                   --packVersion ${{ steps.version.outputs.VERSION }} `
                   --packDir ./publish `
                   -o $env:Release_Directory `
                   --target win-x64

      - name: List files in Releases directory after Velopack
        shell: pwsh
        run: |
          Get-ChildItem -Path $env:Release_Directory -Recurse

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: GlyCounter ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: ${{ env.Release_Directory }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
