name: Build and Publish .NET

on:
  push:
    branches:
      - vishnu/create-github-actions-workflow-for-build
  pull_request:
    branches:
      - vishnu/create-github-actions-workflow-for-build

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: vrtejus/glycounter:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore GlyCounter/GlyCounter.csproj

      - name: Build
        run: dotnet build GlyCounter/GlyCounter/GlyCounter.csproj --configuration Release --output ./build

      - name: Publish
        run: dotnet publish GlyCounter/GlyCounter/GlyCounter.csproj --configuration Release --output ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GlyCounter
          path: ./publish
