name: Build and Release

on:
  # Trigger when pushing to 'master' or pushing any tag that starts with "v"
  push:
    branches: [master]
    tags:
      - "v*"
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write # Needed to create GitHub releases

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: GlyCounter/GlyCounter.sln
      Configuration: Release
      Project_Path: GlyCounter/GlyCounter/GlyCounter.csproj
      Release_Directory: ./Releases
      App_Package_ID: GlyCounter

    steps:
      # 1) Check out repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # So we can read tags/commits if needed

      # 2) Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3) Calculate and update version in csproj from tag or commit count
      - name: Calculate version
        id: version
        shell: pwsh
        run: |
          # Grab total commits for fallback versioning
          $commitCount = git rev-list --count HEAD
          $shortSha = git rev-parse --short HEAD

          # We'll start with "0.0" as base, then commitCount as patch
          $baseVersion = "0.0"
          $versionString = "$baseVersion.$commitCount"
          $fullVersion = "$versionString+$shortSha"

          # Detect if this run was triggered by a tag "vX.Y.Z"
          $isTagPush = $env:GITHUB_REF.StartsWith('refs/tags/v')
          if ($isTagPush) {
            # Extract just the numeric part from the tag, e.g. "v1.2.3" -> "1.2.3"
            $tagVersion = $env:GITHUB_REF.Replace('refs/tags/v', '')

            # If there's a dash (e.g., "1.2.3-beta"), take only the part before dash
            if ($tagVersion -match '-') {
              $versionString = $tagVersion.Split('-')[0]
            } else {
              $versionString = $tagVersion
            }

            # Ensure we have at least 3 parts (Major.Minor.Patch)
            $versionParts = $versionString.Split('.')
            while ($versionParts.Length -lt 3) {
              $versionParts += "0"
            }
            $versionString = $versionParts -join '.'
            $fullVersion = $versionString
          }

          # Validate we have a SemVer (e.g. 1.2.3)
          if (-not ($versionString -match '^\d+\.\d+\.\d+$')) {
            Write-Error "Calculated version '$versionString' is not valid SemVer."
            exit 1
          }

          Write-Host "Calculated version = $versionString"

          # Expose these as outputs for subsequent steps
          echo "VERSION=$versionString" >> $env:GITHUB_OUTPUT
          echo "FULL_VERSION=$fullVersion" >> $env:GITHUB_OUTPUT

          # Update the .csproj with these version numbers
          $csprojPath = "$($env:Project_Path)"
          if (Test-Path $csprojPath) {
            $csproj = Get-Content $csprojPath -Raw
            # Typically AssemblyVersion/FileVersion want 4 parts, e.g. "1.2.3.0"
            $assemblyFileVersion = "$versionString.0"

            $csproj = $csproj -replace '<Version>.*?</Version>', "<Version>$versionString</Version>"
            $csproj = $csproj -replace '<AssemblyVersion>.*?</AssemblyVersion>', "<AssemblyVersion>$assemblyFileVersion</AssemblyVersion>"
            $csproj = $csproj -replace '<FileVersion>.*?</FileVersion>', "<FileVersion>$assemblyFileVersion</FileVersion>"

            Set-Content $csprojPath $csproj
          }
          else {
            Write-Error "Could not find csproj at $csprojPath"
            exit 1
          }

      # 4) Restore dependencies
      - name: Restore dependencies
        run: dotnet restore $env:Solution_Name

      # 5) Build solution
      - name: Build
        run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore

      - name: Test
        run: dotnet test $env:Solution_Name --configuration $env:Configuration --no-build --verbosity normal

      # 6) Publish EXE into "publish/" folder
      - name: Publish Application Executable
        shell: pwsh
        run: |
          dotnet publish $env:Project_Path `
            --configuration $env:Configuration `
            --output ./publish `
            --no-build `
            --self-contained true `
            -r win-x64 `
            /p:PublishSingleFile=false `
            /p:IncludeNativeLibrariesForSelfExtract=false

          if (-not (Test-Path "./publish/GlyCounter.exe")) {
            Write-Host "ERROR: GlyCounter.exe not found after publish."
            exit 1
          }

      # 7) Install VeloPack CLI
      - name: Install Velopack Tool (vpk)
        run: dotnet tool install -g vpk --ignore-failed-sources

      # 8) Pack with VeloPack
      - name: Run Velopack Pack
        shell: pwsh
        run: |
          vpk pack `
            --packId $env:App_Package_ID `
            --packVersion ${{ steps.version.outputs.VERSION }} `
            --packDir ./publish `
            -o $env:Release_Directory `
            --target win-x64
          # ^ Generates .nupkg, releases.win.json, Setup.exe, etc. in ./Releases

      # 9) List Release files (for debugging)
      - name: List files in Releases directory after Velopack
        shell: pwsh
        run: |
          Write-Host "Contents of Releases directory ($($env:Release_Directory)) after Velopack:"
          Get-ChildItem -Path $env:Release_Directory -Recurse | ForEach-Object {
            Write-Host $_.FullName
          }

      # 10) Create or Update GitHub Release (only if we pushed a version tag)
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: GlyCounter ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: ${{ env.Release_Directory }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
